[tool.briefcase]
project_name = "SpectraSight"
bundle = "com.spectrasight"
version = "2.6"
description = "Advanced ethical vulnerability scanner and exploit tester"
author = "SpectraSec"
author_email = "spectra@example.com"
url = "https://github.com/RkNuViPRaSyS/Spectra26"

[tool.briefcase.app.spectrasight]
formal_name = "SpectraSight"
source = "src/spectrasight"
requires = []

[tool.briefcase.app.spectrasight.android]
build_gradle_dependencies = [
  "androidx.appcompat:appcompat:1.0.2",
  "androidx.constraintlayout:constraintlayout:1.1.3",
  "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0",
]