[tool.briefcase]
project_name = "SpectraSight"
bundle = "com.spectrasight"
version = "2.6"
author = "Your Name"
author_email = "your@email.com"
url = "https://github.com/RkNuViPRaSyS/Spectra26"
license = "MIT"
description = "Advanced Android vulnerability scanner with GUI and smart logic."

[tool.briefcase.app.spectrasight]
formal_name = "SpectraSight"
description = "Powerful vulnerability scanner for Android"
sources = ["src/spectrasight"]
entry_point = "spectrasight.app:main"  # ✅ Add this line

[tool.briefcase.app.spectrasight.android]
gradle_dependencies = [
  "androidx.appcompat:appcompat:1.0.2",
  "androidx.constraintlayout:constraintlayout:1.1.3",
  "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
]
