name: build-apk

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull BeeWare Docker image
        run: docker pull beeware/briefcase

      - name: Build APK inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app beeware/briefcase \
            bash -c "pip install -U briefcase && briefcase create android && briefcase build android && briefcase package android"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SpectraSight-APK
          path: dist/SpectraSight/android/*.apk
