name: build-apk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting build..."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build APK with Briefcase
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Show dist folder contents
        run: ls -R dist/

      - name: Locate APK file and upload it
        run: |
          echo "Searching for APK files..."
          find dist/ -name "*.apk" || true

      - name: Upload any found APKs
        uses: actions/upload-artifact@v4
        with:
          name: SpectraSight-APK
          path: dist/**/*.apk
