name: build-apk

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create Android project
        run: briefcase create android

      - name: Build Android project
        run: briefcase build android

      - name: Package Android APK
        run: briefcase package android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpectraSight-APK
          path: dist/SpectraSight/android/*.apk

