name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create Android project
        run: |
          briefcase create android

      - name: Build APK
        run: briefcase build android

      - name: List APK build output (DEBUG)
        run: ls -R build/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: build-apk
          path: dist/*.apk
