name: build-apk

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Briefcase and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip curl libglib2.0-0
          pip install --upgrade pip
          pip install briefcase

      - name: Create & Build APK
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpectraSight-APK
          path: dist/SpectraSight/android/*.apk
